apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npminstall
spec:
  steps:
    - name: install
      image: node:16
      script: npm install
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine
spec:
  steps:
    - name: test
      image: node:16
      script: npx jasmine
